#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
using namespace std;

namespace Color {
    const string RED = "\033[31m";
    const string GREEN = "\033[32m";
    const string YELLOW = "\033[33m";
    const string RESET = "\033[0m";
}

const int comnum = 100;

ifstream in("main.qkl");
ofstream out("temp.asm");

string commands[comnum] = { "end", "var", "POINT", "call", "jump", "term", "if" };
string arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9;

void chknocom();
void chkcom();


void mov(string farg0, string farg1);
void sub(string farg0, string farg1);
void add(string farg0, string farg1);
void int_(string farg0);
void jump(string farg0);
void call(string farg0);
void anytext(string farg0);

int main(int argc, char* argv[])
{
    if (argc < 2) {
        cout << Color::RED << "ERROR: " << Color::RESET << "Input file isn't specified!" << endl;
        cout << Color::YELLOW << "EXAMPLE: " << Color::RESET << "./compile main.qkl -o main.asm" << endl;
        return 1;
    }


    string inputFile = argv[1];
    string outputFile = "main.asm";

    if (argc >= 4) {
        string secondArg = argv[2];
        if (secondArg == "to" || secondArg == "-o" || secondArg == "--output") {
            outputFile = argv[3];
        }
    } else if (argc >= 3) {
        outputFile = argv[2];
    }


    string line;

    if (in.is_open() && out.is_open())
    {
        anytext("; code generated by the Quark language compiler v0.1.0");
        while (getline(in, line))
        {
            if (line.empty()) continue;
            istringstream iss(line);
                iss >> arg0;

                if (arg0 == "asm:") {
                    string restOfLine;
                    getline(iss, restOfLine);
                    if (!restOfLine.empty()) {
                        if (restOfLine[0] == ' ') restOfLine.erase(0, 1);
                        out << restOfLine << endl;
                    }
                    continue;
                }

                iss >> arg1 >> arg2 >> arg3 >> arg4 >> arg5 >> arg6 >> arg7 >> arg8 >> arg9;

            chkcom();
            if(arg0 == ";") continue;
            else {
                bool fnd = false;
                for (int i = 0; i<comnum; i++){
                    if(!commands[i].empty() && arg0 == commands[i]){
                        fnd = true;
                        break;
                    }

                }
                if (!fnd) chknocom();

            }
        }

    }
    in.close();
    out.close();
}

void chknocom(){
    if(arg1 == "=") mov(arg0, arg2);
    else if(arg1 == "+="){
        mov("al", arg0);
        add("al", arg2);
        mov(arg0, "al");
    }
    else if(arg1 == "-=") {
        mov("al", arg0);
        sub("al", arg2);
        mov(arg0, "al");
    }
    else if(arg1 == "++") {
        anytext("inc " + arg0);
    }
    else if(arg1 == "--") {
        anytext("dec " + arg0);
    }
    else if(arg1 == "<tochar>"){
        mov("al", arg0);
        add("al", "'0'");
        mov(arg0, "al");
    }
    else if(arg1 == "<tonum>"){
        mov("al", arg0);
        sub("al", "'0'");
        mov(arg0, "al");
    }

}
void chkcom(){
    if(arg0 == "end") jump("$");
    else if(arg0 == "printch"){
        mov("ah", "0x0e");
        mov("al", arg1);
        int_("0x10");
    }
    else if(arg0 == "readch"){
        mov("ah", "0x00");
        int_("0x16");
        if (arg1 != ":NULL"){
            mov(arg1, "ah");
        }
        if (arg2 != ":NULL"){
            mov(arg2, "al");
        }
    }
    else if(arg0 == "var"){
        if(arg2 == "=") anytext(arg1 + " db " + arg3);
        else anytext(arg1 + " db 0");
    }
    else if (arg0 == "if") {
        mov("al", arg1);
        out << "cmp al, " << arg3 << endl;
        if (arg2 == "!=") out << "jne " << arg5 << endl;
        else if (arg2 == "==") out << "je " << arg5 << endl;
        else if (arg2 == ">=")  out << "jbe " << arg5 << endl;
        else if (arg2 == "<=")  out << "jae " << arg5 << endl;
        else if (arg2 == ">")  out << "jb " << arg5 << endl;
        else if (arg2 == "<")  out << "ja " << arg5 << endl;
    }
    else if(arg0 == "POINT") anytext(arg1);
    else if(arg0 == "term") anytext("ret");
    else if(arg0 == "jump") jump(arg1);
    else if(arg0 == "call") call(arg1);


    // else cout << Color::YELLOW << "NOTE: " << Color::RESET << Color::GREEN << arg0 << Color::RESET << " - unknown command" << endl;

}

void mov(string farg0, string farg1){
    out << "mov " << farg0 << ", " << farg1 << endl;
}
void sub(string farg0, string farg1){
    out << "sub " << farg0 << ", " << farg1 << endl;
}
void add(string farg0, string farg1){
    out << "add " << farg0 << ", " << farg1 << endl;
}
void int_(string farg0){
    out << "int " << farg0 << endl;
}
void jump(string farg0){
    out << "jmp " << farg0 << endl;
}
void call(string farg0){
    out << "call " << farg0 << endl;
}
void anytext(string farg0){
    out << farg0 << endl;
}
