#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
using namespace std;

namespace Color {
    const string RED = "\033[31m";
    const string GREEN = "\033[32m";
    const string YELLOW = "\033[33m";
    const string RESET = "\033[0m";
}

const int comnum = 100;
const int argnum = 9;

ifstream in;
ofstream out;

string commands[comnum] = { "end", "var", "POINT", "call", "jump", "term", "if", "include" };
string arg[argnum];
string current_line;

void chknocom();
void chkcom();


void mov(string farg0, string farg1);
void sub(string farg0, string farg1);
void add(string farg0, string farg1);
void int_(string farg0);
void jump(string farg0);
void call(string farg0);
void anytext(string farg0);

int main(int argc, char* argv[])
{
    if (argc < 2) {
        cout << Color::RED << "ERROR: " << Color::RESET << "Input file isn't specified!" << endl;
        cout << Color::YELLOW << "EXAMPLE: " << Color::RESET << "./compile input.qkl -o output.asm" << endl;
        return 1;
    }


    string inputFile = argv[1];
    string outputFile = argv[2];

    if (argc >= 4 && string(argv[2]) == "-o") {
        outputFile = argv[3];
    } else if (argc >= 3) {
        outputFile = argv[2];
    }

    in.open(inputFile);
    out.open(outputFile);

    string line;

    cout << Color::GREEN << "compiling..." << endl;
    if (in.is_open() && out.is_open())
    {
        anytext("; code generated by the Quark language compiler v0.1.1");
        while (getline(in, line))
        {
            if (line.empty()) continue;
            istringstream iss(line);
            current_line = line;

                iss >> arg[0];

                if (arg[0] == "asm:") {
                    string restOfLine;
                    getline(iss, restOfLine);
                    if (!restOfLine.empty()) {
                        if (restOfLine[0] == ' ') restOfLine.erase(0, 1);
                        out << restOfLine << endl;
                    }
                    continue;
                }

                iss >> arg[1] >> arg[2] >> arg[3] >> arg[4] >> arg[5] >> arg[6] >> arg[7] >> arg[8] >> arg[9];

            chkcom();
            if(arg[0] == ";") continue;
            else {
                bool fnd = false;
                for (int i = 0; i<comnum; i++){
                    if(!commands[i].empty() && arg[0] == commands[i]){
                        fnd = true;
                        break;
                    }

                }
                if (!fnd) chknocom();

            }
        }

    } else {
        cout << Color::RED << "ERROR: " << Color::RESET << "Error opening files" << endl;
        if (!in.is_open()) {
            cout << Color::RED << "Cannot open input file: " << inputFile << Color::RESET << endl;
        }
        if (!out.is_open()) {
            cout << Color::RED << "Cannot create output file: " << outputFile << Color::RESET << endl;
        }
        return 1;
    }
    in.close();
    out.close();

}

void chknocom(){
    if(arg[3] == "=") mov(arg[0], arg[2]);
    else if(arg[1] == "+="){
        mov("al", arg[0]);
        add("al", arg[2]);
        mov(arg[0], "al");
    }
    else if(arg[1] == "-=") {
        mov("al", arg[0]);
        sub("al", arg[2]);
        mov(arg[0], "al");
    }
    else if(arg[1] == "++") {
        anytext("inc " + arg[0]);
    }
    else if(arg[1] == "--") {
        anytext("dec " + arg[0]);
    }
    else if(arg[1] == "<tochar>"){
        mov("al", arg[0]);
        add("al", "'0'");
        mov(arg[0], "al");
    }
    else if(arg[1] == "<tonum>"){
        mov("al", arg[0]);
        sub("al", "'0'");
        mov(arg[0], "al");
    }

}
void chkcom(){
    if(arg[1] == "end") jump("$");
    else if(arg[0] == "printch"){
        mov("ah", "0x0e");
        mov("al", arg[1]);
        int_("0x10");
    }
    else if(arg[0] == "readch"){
        mov("ah", "0x00");
        int_("0x16");
        if (arg[1] != ":NULL"){
            mov(arg[1], "ah");
        }
        if (arg[2] != ":NULL"){
            mov(arg[2], "al");
        }
    }
    else if(arg[0] == "var"){
        if(arg[2] == "=") {
            size_t eq = current_line.find('=');
            if (eq != string::npos) {
                string val = current_line.substr(eq + 1);
                val.erase(0, val.find_first_not_of(" \t"));
                anytext(arg[1] + " db " + val);
            } else {
                anytext(arg[1] + " db 0");
            }
        }
        else anytext(arg[1] + " db 0");
    }
    else if (arg[0] == "if") {
        mov("al", arg[1]);
        out << "cmp al, " << arg[3] << endl;
        if (arg[2] == "!=") out << "jne " << arg[5] << endl;
        else if (arg[2] == "==") out << "je " << arg[5] << endl;
        else if (arg[2] == "<=")  out << "jbe " << arg[5] << endl;
        else if (arg[2] == ">=")  out << "jae " << arg[5] << endl;
        else if (arg[2] == "<")  out << "jb " << arg[5] << endl;
        else if (arg[2] == ">")  out << "ja " << arg[5] << endl;
    }
    else if(arg[0] == "POINT") anytext(arg[1]);
    else if(arg[0] == "term") anytext("ret");
    else if(arg[0] == "include") anytext("%INCLUDE " + arg[1]);
    else if(arg[0] == "jump") jump(arg[1]);
    else if(arg[0] == "call") call(arg[1]);


    // else cout << Color::YELLOW << "NOTE: " << Color::RESET << Color::GREEN << arg[0] << Color::RESET << " - unknown command" << endl;

}

void mov(string farg0, string farg1){
    out << "mov " << farg0 << ", " << farg1 << endl;
}
void sub(string farg0, string farg1){
    out << "sub " << farg0 << ", " << farg1 << endl;
}
void add(string farg0, string farg1){
    out << "add " << farg0 << ", " << farg1 << endl;
}
void int_(string farg0){
    out << "int " << farg0 << endl;
}
void jump(string farg0){
    out << "jmp " << farg0 << endl;
}
void call(string farg0){
    out << "call " << farg0 << endl;
}
void anytext(string farg0){
    out << farg0 << endl;
}
